//
// Created by dimitrisgan on 25/2/2019.
//

#ifndef TRANSACTIONBITCOINSYSTEM_DATASTRUCTURES_H
#define TRANSACTIONBITCOINSYSTEM_DATASTRUCTURES_H




#endif //TRANSACTIONBITCOINSYSTEM_DATASTRUCTURES_H
